### ISSUE TITLE
feature: basic app function

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/pss2k24-arrowflicks#1]
## Task
Implement basic app functionality, with all import packages installed.
Just a basic page with h1 in the center.

### This package has to work correctly:
- [ ] eslint
- [ ] prettier
- [ ] lint-staged
- [ ] Husky
- [ ] vitest
- [ ] Mantine

### What have to work

- [ ] lifecycle scripts in package.json
- [ ] lint of staged files
- [ ] test before push
- [ ] main page opens with one h1
